swagger: '2.0'
info:
  version: 0.0.1
  title: DataMiningCloud Repository Service
  description: An API specification of DMC Repository based on swagger-2.0 specification
  contact:
    name: Aid
    email: aid666@gmail.com
  license:
    name: MIT
    url: 'http://opensource.org/licenses/MIT'
basePath: /repo
schemes:
  - http
consumes:
  - application/json
  - application/xml
produces:
  - application/json
  - application/xml
paths:

  /jobs:
    get:
      tags:
      - jobs
      parameters:
      - name: tags
        in: query
        description: tags to filter by
        required: false
        type: array
        items:
          type: string
        collectionFormat: csv
      - name: name
        in: query
        description: "DMJob's type to filter by"
        required: false
        type: string
      - name: type
        in: query
        description: "DMJob's type to filter by"
        required: false
        type: string
      - name: domain
        in: query
        description: "DMJob's domain to filter by"
        required: false
        type: string
      - name: locale
        in: query
        description: "DMJob's locale to filter by"
        required: false
        type: string
      - name: limit
        in: query
        description: maximum number of results to return
        required: false
        type: integer
        format: int32
      - name: start
        in: query
        description: start index of response entities list
        required: false
        type: integer
        format: int32
      - name: orderby
        in: query
        description: the order factor of the list.
        required: false
        type: string
      responses:
        200:
          description: DMJob Metadata List
          schema:
            type: array
            items:
              $ref: '#/definitions/DMJobMetadata'
    post:
      tags:
      - jobs
      description: "Create a new DM Job"
      parameters:
      - in: body
        name: body
        schema:
          $ref: "#/definitions/DMJobMetadata"
      responses:
        201:
          description: OK
          schema:
              $ref: '#/definitions/DMJobMetadata'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/errorModel'

  /jobs/{jobKey}:
    get:
      tags:
      - jobs
      summary: Get metadata of DM Job
      description: Return the medata of DM Job based on the jobKey
      parameters:
      - in: path
        name: jobKey
        description: "The generated key of a DM Job"
        type: string
      responses:
        200:
          description: OK
          schema:
              $ref: '#/definitions/DMJobMetadata'
    put:
      tags:
      - jobs
      summary: Update metadata of DM job
      description: Update the medata of DM job based on the jobKey
      parameters:
      - in: path
        name: jobKey
        description: "The generated key of a DMJob"
        type: string
      - in: body
        name: body
        description: "The new DMJob"
        schema:
          $ref: "#/definitions/DMJobMetadata"
      responses:
        200:
          description: OK
          schema:
              $ref: '#/definitions/DMJobMetadata'
    delete:
      tags:
      - jobs
      summary: Remove the whole DM job
      description: Remove the medata, archive, processers, input and outpu, not including related model.
      parameters:
      - in: path
        name: jobKey
        type: string
      responses:
        204:
          description: OK

  /jobs/{jobKey}/processers:
    get:
      tags:
      - jobs
      parameters:
      - in: path
        name: jobKey
        type: string
      responses:
        "200":
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/Processer'
    put:
      tags:
      - jobs
      description: If this job has been build already, use that deployed ProcessFlow to handle the data. Otherwise an ad_hoc execute will be run.
      parameters:
      - in: path
        name: jobKey
        description: "The generated key of a DMJob"
        type: string
      - in: body
        name: body
        schema:
          type: array
          items:
            $ref: "#/definitions/Processer"
      responses:
        200:
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/Processer'

  /jobs/{jobKey}/build:
    post:
      tags:
      - jobs
      parameters:
      - in: path
        name: jobKey
        type: string
      responses:
        201:
            description: OK
            schema:
              $ref: '#/definitions/ServiceFlow'

  /models:
    get:
      tags:
      - model
      parameters:
      - name: tags
        in: query
        description: tags to filter by
        required: false
        type: array
        items:
          type: string
        collectionFormat: csv
      - name: name
        in: query
        description: "Model's name to filter by"
        required: false
        type: string
      - name: type
        in: query
        description: "Model's type to filter by"
        required: false
        type: string
      - name: domain
        in: query
        description: "Model's domain to filter by"
        required: false
        type: string
      - name: locale
        in: query
        description: "Model's locale to filter by"
        required: false
        type: string
      - name: trainerType
        in: query
        description: "Model's trainer type to filter by"
        required: false
        type: string
      - name: referenceCountLowLimit
        in: query
        description: The minium reference count to filter by
        type: integer
        format: int32
      - name: limit
        in: query
        description: maximum number of results to return
        required: false
        type: integer
        format: int32
      - name: start
        in: query
        description: start index of response entities list
        required: false
        type: integer
        format: int32
      - name: orderby
        in: query
        description: the order factor of the list.
        required: false
        type: string
      responses:
        200:
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/ModelMetadata'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/errorModel'
    post:
      tags:
      - model
      description: "Create a new DM Processer Model"
      parameters:
      - in: body
        name: body
        schema:
          $ref: "#/definitions/ModelBuildRequest"
      responses:
        201:
          description: OK
          schema:
             $ref: '#/definitions/ModelMetadata'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/errorModel'

  /models/{modelKey}:
    get:
      tags:
      - model
      summary: Get metadata of DM Service
      description: Return the medata of model based on the jobKey
      parameters:
      - in: path
        name: modelKey
        description: "The generated key of a Processer model"
        type: string
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/ModelMetadata'
    put:
      tags:
      - model
      parameters:
      - in: path
        name: modelKey
        description: "The generated key of a Processer model"
        type: string
      - in: body
        name: body
        schema:
          $ref: '#/definitions/ModelMetadata'
      responses:
        201:
          description: OK
          schema:
              $ref: '#/definitions/ModelMetadata'
    delete:
      tags:
      - model
      parameters:
      - in: path
        name: modelKey
        type: string
      responses:
        204:
          description: OK

  /models/{modelKey}/data:
    get:
      tags:
      - model
      summary: Get data of DM Model
      parameters:
      - in: path
        name: modelKey
        type: string
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/ModelData'
    put:
      tags:
      - model
      summary: Get data of DM Model
      parameters:
      - in: path
        name: modelKey
        type: string
      - in: body
        name: body
        schema:
          $ref: '#/definitions/ModelData'
      responses:
        201:
          description: OK
          schema:
            $ref: '#/definitions/ModelData'

  /models/{modelKey}/builds:
    get:
      tags:
      - model
      description: Return the build of the trainer's build.
      parameters:
      - in: path
        name: modelKey
        type: string
      responses:
        200:
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/TrainerBuildMetadata'
    post:
      tags:
      - model
      description: Add a new build to the build history
      parameters:
      - in: path
        name: modelKey
        description: "The generated key of a Processer model build"
        type: string
      - in: body
        name: body
        description: Training set and trainer, maybe the build history the trainer support the updateable trainer.
        schema:
          $ref: '#/definitions/ModelBuildRequest'
      responses:
        201:
          description: OK
          schema:
            $ref: '#/definitions/TrainerBuildMetadata'

  /models/{modelKey}/builds/{buildKey}:
    get:
      tags:
      - model
      description: Return the build of the trainer's build.
      parameters:
      - in: path
        name: modelKey
        type: string
      - in: path
        name: buildKey
        type: string
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/TrainerBuildMetadata'

    delete:
      tags:
      - model
      description: Delete the build from the build history
      parameters:
      - in: path
        name: modelKey
        description: "The generated key of a Processer model build"
        type: string
      responses:
        204:
          description: OK

  #Archives jobs.
  /archives/job:
    get:
      tags:
      - archive
      responses:
        200:
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/ServiceArchiveMetadata'
    post:
      tags:
      - archive
      parameters:
        - in: body
          name: body
          schema:
            $ref: '#/definitions/ServiceArchive'
      responses:
        201:
          description: OK
          schema:
            $ref: '#/definitions/ServiceArchiveMetadata'

  /archives/job/{archiveKey}:
    get:
      tags:
      - archive
      parameters:
      - in: path
        name: archiveKey
        type: string
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/ServiceArchive'
    delete:
      tags:
      - archive
      parameters:
      - in: path
        name: archiveKey
        type: string
      responses:
        204:
          description: OK

  /archives/model:
    get:
      tags:
      - archive
      responses:
        200:
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/ModelArchiveMetadata'
    post:
      tags:
      - archive
      parameters:
      - in: body
        name: body
        schema:
          $ref: '#/definitions/ModelArchive'
      responses:
        201:
          description: OK
          schema:
            $ref: '#/definitions/ModelArchiveMetadata'

  /archives/model/{archiveKey}:
    get:
      tags:
      - archive
      parameters:
      - in: path
        name: archiveKey
        type: string
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/ModelArchive'
    delete:
      tags:
      - archive
      parameters:
        - in: path
          name: archiveKey
          type: string
      responses:
        204:
          description: OK

definitions:
  Domain:
    properties:
      name:
        type: string
      date:
        description: The domain in differnent date may different, think about the change of computer brand from 1995 to 2015 .
        type: string
      parentDomain:
        $ref: '#/definitions/Domain'

  DMData:
    properties:
      key:
        type: string
      data:
        type: array
        items:
         $ref: '#/definitions/ColumnData'

  ColumnData:
    properties:
      attribute:
        $ref: '#/definitions/Attribute'
      data:
        type: array
        items:
          type: string

  DataInfor:
    properties:
      name:
        type: string
      domain:
        $ref: '#/definitions/Domain'

  Attribute:
    properties:
      name:
        type: string
      type:
        type: string
      format:
        type: string
      dataInfor:
        $ref: '#/definitions/DataInfor'

  DMJobMetadata:
    required:
      - key
    properties:
      key:
        type: string
      name:
        type: string
      description:
        type: string
      tags:
        type: array
        items:
          type: string
      domain:
        $ref: '#/definitions/Domain'
      type:
        type: string
      isPublic:
        type: boolean
      owner:
        type: string

  ProcesserAlgorithm:
    properties:
      key:
        type: string
      name:
        type: string
      description:
        type: string
      tags:
        type: array
        items:
          type: string
      catalog:
        description: The catelog path of the trainer, classifier.decisionTree.id3
        type: string

  Processer:
    properties:
      modelRef:
        $ref: '#/definitions/Reference'
      algrithm:
        $ref: '#/definitions/ProcesserAlgorithm'

  Reference:
    properties:
      refResource:
        type: string
      refKey:
        type: string
      refType:
        type: string
      accessCode:
        type: string

  ServiceArchiveMetadata:
    required:
    - key
    properties:
      key:
        type: string
      name:
        type: string
      description:
        type: string
      tags:
        type: array
        items:
          type: string
      domain:
        $ref: '#/definitions/Domain'
      type:
        type: string
      isPublic:
        type: boolean
      owner:
        type: string

  ServiceArchive:
    properties:
      metadata:
        $ref: '#/definitions/ServiceArchiveMetadata'
      content:
        type: string

  ServiceFlow:
    properties:
      key:
        type: string

  ModelMetadata:
    required:
    - key
    properties:
      key:
        type: string
      name:
        type: string
      description:
        type: string
      tags:
        type: array
        items:
          type: string
      domain:
        $ref: '#/definitions/Domain'
      type:
        type: string
      isPublic:
        type: boolean
      owner:
        type: string

  ModelBuildRequest:
    properties:
      metadata:
        $ref: '#/definitions/ModelMetadata'
      trainSet:
        $ref: '#/definitions/DMData'
      trainer:
        $ref: '#/definitions/Reference'

  ModelData:
    properties:
      name:
        type: string
      data:
        $ref: '#/definitions/DMData'

  ModelArchiveMetadata:
    required:
      - key
    properties:
      key:
        type: string
      name:
        type: string
      description:
        type: string
      tags:
        type: array
        items:
          type: string
      domain:
        $ref: '#/definitions/Domain'
      type:
        type: string
      isPublic:
        type: boolean
      owner:
        type: string

  ModelArchive:
    properties:
      metadata:
        $ref: '#/definitions/ModelArchiveMetadata'
      content:
        type: string

  errorModel:
    required:
      - code
      - message
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
